---
output: github_document
---

# Praktische Anleitungen für Break-Even-Ziele {-#be}

<div class="subtitle">Praktische Anleitung, wie Fortschritte auf dem Weg zur future-fitness (Zukunftsfähigkeit) erzielt und gemessen werden können.
</div>

Diese Anleitungen wurden speziell entwickelt, um Ihnen zu helfen die [Break-Even Ziele](#mg-be) in Ihren Geschäftsbetrieb einzubetten. Die Absicht ist nicht, das Rad neu zu erfinden: Wo immer möglich, wurden die besten Expert-Resourcen zusammengestellt und entsprechend in der [Biobliografie](#bibliography) der Benchmark referenziert. 

Sie können sich jede Praktische Anleitung als Einstiegspunkt vorstellen, der Ihnen ausreichend Details gibt, um loszulegen, und sie bei Bedarf auf zusätzliche Information hinweist. Praktische Anleitungen, bestehen aus fünf Abschnitten, die im Folgenden beschrieben werden. 

##### 1. Ambition {-}

Der Abschnitt _Ambition_ beginnt mit einer detaillierten Beschreibung des Ziels. Als nächstes gibt es eine Handvoll Statistiken, die veranschaulichen, warum die Lösung dieses speziellen Problems so wichtig ist. Diese können sich als nützlich erweisen, wenn es darum geht, andere Menschen von der Bedeutung des Ziels zu überzeugen.

Anschließend finden Sie Informationen zum Zusammenhang des Ziels mit den SDGs. Es erklärt, warum die Verfolgung des Ziels dem Unternehmen hilft, die Möglichkeit auszuschließen, dass es den kollektiven Fortschritt der Gesellschaft unbeabsichtigt untergräbt.

Abschließend wird kurz erläutert, wie sich das Ziel von den anderen Break-Even-Zielen unterscheidet und diese ergänzt. Dies soll Ihnen ein Gespür für die Zusammenhänge zwischen den das Unternehmen betreffenden Problemen vermitteln und Ihnen dabei helfen, diese ganzheitlich zu verstehen und anzugehen.

##### 2. Aktion {-}

Der Abschnitt _Aktion_ ist in zwei Teile unterteilt: _Erste Schritte_ und _Zukunftsfähigkeit anstreben_.

_Erste Schritte_ bieten Hintergrundinformationen dazu, wie man über das Ziel nachdenkt, und bieten eine Reihe von Fragen, die sich das Unternehmen stellen kann. Diese Fragen sollen Ihnen dabei helfen, zu überprüfen, was Sie bereits wissen, mögliche Wissenslücken zu erkennen und Ihnen Anregungen für eine Priorisierung zu geben.

_Zukunftsfähigkeit anstreben_ geht detailliert auf die Schritte ein, die das Unternehmen unternehmen muss, um zukunftsfähig zu werden. Hier finden Sie häufig Verweise auf Ressourcen Dritter, die für Sie hilfreich sein könnten.

##### 3. Assessment {-}

Der Abschnitt _Assessment_ konzentriert sich darauf, wie der Fortschritt in Richtung des Ziels gemessen werden kann. Die Indikatoren sollen eine umfassende Möglichkeit zur Beobachtung des Fortschritts auf Organisationsebene bieten, jedoch mit ausreichender Granularität, damit Sie beurteilen können, wie sich alltägliche Entscheidungen auf diesen Fortschritt auswirken. 

Es gibt zwei Arten von Indikatoren: Fortschrittsindikatoren und Kontextindikatoren.

###### Fortschrittsindikatoren {-}

Fortschrittsindikatoren werden als einfache Prozentzahl ausgedrückt und geben an, wie weit das Unternehmen gekommen ist – und wie weit es noch gehen muss –, um das jeweilige Ziel zu erreichen. Die meisten Ziele haben nur einen Fortschrittsindikator.

Fortschrittsindikatoren sollen nach Möglichkeit den Zusammenhang zwischen außerfinanzieller Leistung und finanzieller Leistung erkennen:

-	Alle Ziele rund um Produkte – etwa „Produkte schaden weder Mensch noch Umwelt“ – verfügen über Fortschrittsindikatoren, die nach dem Umsatz gewichtet werden. Wenn also ein einzelnes Produkt einen Großteil des Umsatzes des Unternehmens ausmacht, wird dessen Leistung einen ähnlich großen Einfluss auf die Fortschrittsanzeige haben. Dieser größere Einfluss spiegelt die Tatsache wider, dass das Produkt mehr zum Unternehmenserfolg beiträgt.

-	Ebenso verfügen Ziele, die sich auf den Ressourceneinsatz des Unternehmens beziehen – wie z. B. Beschaffung sichert das Streben nach Zukunftsfähigkeit – über Fortschrittsindikatoren, die nach Kosten gewichtet sind. In diesen Fällen liegen die größten Möglichkeiten für Fortschritt dort, wo das Unternehmen am meisten Geld ausgibt.

Fortschrittsindikatoren für alle Ziele könnten problemlos auf einer einzigen Bildschirmseite oder einer gedruckten Seite dargestellt werden, beispielsweise als Dashboard, um es regelmäßig mit dem Führungsteam des Unternehmens zu teilen.

###### Kontextindikatoren {-}

Jeder Fortschrittsindikator wird durch einen oder mehrere Kontextindikatoren ergänzt. Diese geben zusätzliche Informationen über das Ausmaß der erzielten Fortschritte. Beispielsweise erfasst der Fortschrittsindikator für das Ziel des existenz-sichernden Lohns lediglich den Anteil der Arbeitnehmer, die mindestens einen existenz-sichernden Lohn erhalten. Für dieses Ziel gibt es einen Kontextindikator, nämlich die Gesamtzahl der Arbeitnehmer.

Stellen Sie sich vor, dass zwei Unternehmen jeweils 30% ihrer Arbeitnehmer unterbezahlen. Das Ausmaß dieses Defizits ist sehr unterschiedlich, wenn eines dieser Unternehmen 20 Mitarbeiter beschäftigt und das andere 20.000. Es ist wichtig, den Fortschritt in einen Kontext zu stellen, um einen Gesamteindruck für die Leistung des Unternehmens zu erhalten.

##### 4. Assurance {-}

Irgendwann möchte ein Unternehmen vielleicht damit beginnen, öffentlich über seinen Weg zur Zukunftsfähigkeit zu sprechen. Durch die Selbstbewertung entfällt die Notwendigkeit, vertrauliche Informationen an Bewerter oder andere Organisationen weiterzugeben, um das Unternehmen zu „bewerten“. Aber warum sollten Investoren und andere darauf vertrauen, was ein Unternehmen über seine eigene Leistung sagt?

Diese Frage wurde für die finanzielle Leistung schon vor Jahrzehnten beantwortet: Wenn ein Unternehmen seine Leistung bewertet hat, muss es lediglich einen qualifizierten Dritten beauftragen, die Ergebnisse vor der Offenlegung unabhängig zu prüfen. Der Future-Fit-Ansatz spiegelt dies wider und erweitert das bewährte unabhängige Prüfmodell auf nichtfinanzielle Informationen. Möchte ein Unternehmen also Details zu seinen Fortschritten auf dem Weg zur Zukunftsfähigkeit veröffentlichen, kann es jeden registrierten Wirtschaftsprüfer bitten, seine Berechnungen zu bestätigen. Allerdings weiß der durchschnittliche Unternehmer möglicherweise nicht, wonach ein Prüfer suchen würde – beispielsweise im Hinblick auf die Nachverfolgung, wie Prozesse überwacht und Richtlinien durchgesetzt werden.

Hier kommt der Abschnitt _Assurance_ ins Spiel. Er bietet Hinweise zu den Arten von Beweisen, nach denen Versicherer wahrscheinlich suchen werden, um zu überprüfen, ob das Unternehmen sich selbst richtig beurteilt hat. Dies kann Ihnen dabei helfen, häufige Fallstricke bei der Prüfung zu vermeiden und den Weg zur Veröffentlichung zu erleichtern, falls Sie sich entscheiden, irgendwann über die Zukunftsfähigkeit des Unternehmens zu berichten.

##### 5. Weitere Informationen {-}

Der fünfte und letzte Abschnitt bietet eine Reihe zusätzlicher Materialien, die für Sie hilfreich sein könnten. Dazu gehört ein ausgearbeitetes Beispiel, das erklärt, wie die Indikatoren in der Praxis verwendet werden, sowie eine Reihe nützlicher Links zu Ressourcen Dritter. Viele Praktische Anleitungen enthalten auch eine Reihe zielspezifischer, häufig gestellter Fragen.
